vim.g.mapleader = " "
vim.g.maplocalleader = " "
local map = vim.keymap.set
local silent = { noremap = true, silent = true }
map({ "i", "v" }, "kj", "<Esc>", silent)
map("t", "<Esc><Esc>", "<C-\\><C-n>", silent)
map("n", "j", "gj", silent)
map("n", "k", "gk", silent)
map("v", "<", "<gv", silent)
map("v", ">", ">gv", silent)
map("n", "<leader>w", "<cmd>write<cr>", { desc = "Write" })
map("n", "<leader>q", "<cmd>quit<cr>", { desc = "Quit" })
map("n", "<leader>Q", "<cmd>qa<cr>", { desc = "Quit all" })
map("n", "<leader>h", "<C-w>h", { desc = "Window left" })
map("n", "<leader>j", "<C-w>j", { desc = "Window down" })
map("n", "<leader>k", "<C-w>k", { desc = "Window up" })
map("n", "<leader>l", "<C-w>l", { desc = "Window right" })
map("n", "<leader>bn", "<cmd>bnext<cr>", { desc = "Next buffer" })
map("n", "<leader>bp", "<cmd>bprevious<cr>", { desc = "Previous buffer" })
map("n", "<leader>pv", "<cmd>vsplit<cr>", { desc = "Vertical split" })
map("n", "<leader>ph", "<cmd>split<cr>", { desc = "Horizontal split" })
map("n", "<leader>pe", "<C-w>=", { desc = "Equalize splits" })
map("n", "<leader>px", "<cmd>close<cr>", { desc = "Close split" })
map("n", "<leader>lk", vim.lsp.buf.hover, { desc = "LSP hover" })
map("n", "<leader>ld", vim.lsp.buf.definition, { desc = "Definition" })
map("n", "<leader>lr", vim.lsp.buf.references, { desc = "References" })
map("n", "<leader>lR", vim.lsp.buf.rename, { desc = "Rename" })
map("n", "]d", function() vim.diagnostic.jump({ count = 1, float = true }) end, { desc = "Next diagnostic" })
map("n", "[d", function() vim.diagnostic.jump({ count = -1, float = true }) end, { desc = "Previous diagnostic" })
