export LANG="${LANG:-en_US.UTF-8}"
export EDITOR=nvim VISUAL=nvim
export HISTFILE="$HOME/.zhistory" HISTSIZE=100000 SAVEHIST=100000
setopt APPEND_HISTORY SHARE_HISTORY HIST_IGNORE_ALL_DUPS HIST_REDUCE_BLANKS AUTO_CD INTERACTIVE_COMMENTS
bindkey -v
KEYTIMEOUT=10
autoload -Uz compinit
mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
compinit -d "${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump"
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
[[ -r "$HOME/.alias" ]] && source "$HOME/.alias"
if [[ -r /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]]; then
  source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
  ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
fi
command -v starship >/dev/null 2>&1 && eval "$(starship init zsh)"
# Syntax highlighting must load last.
[[ -r /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] && \
  source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
